### ISSUE TITLE
Important message

### ISSUE THREAD

**Issue by Alexis12119** [brianrbrenner/dotfiles#1]
If I'm correct you used my `nvim-config` and I just want to say I made a lot of improvements and fixes on my [nvim-config](https://github.com/Alexis12119/nvim-config).  If I'm wrong sorry .

**Comment by brianrbrenner** [comment]
Hey yeah I did. The only reason I didn't fork it is because I use a modified version for work. I hope you don't mind that. And I'll take a look! Thanks

**Comment by Alexis12119** [comment]
Yeah I don't mind it and thanks for the star. Have a nice day :)
